### ISSUE TITLE
Can only query a limited date range from the API

### ISSUE THREAD

**Issue by daveebbelaar** [openearth/ddlpy#18]
* Data Distributie Laag. Service from Rijkswaterstaat for distributing water quantity data. version:
* Python version: 3.10
* Operating System: macOS Venture 13.2.1 (22D68)

### Description

I am experiencing some weird issues while trying to interact with the API. We are setting up a data service that can pull new data daily, but also historical data over a given date range. In particular, I am trying to load historical data from station OLST. For this use case, I am attempting to load all the data from this year "2023-01-01" to today. We are interested in the flow (Q) for this station. 

Yesterday, loading the historical data for that date range worked fine, and today I can only get data of the past 30 days or so, getting an error "Geen gegevens beschikbaar" when I try to load "2023-01-01" to "2023-02-01" for example. This behavior has happened before (same machine, same environment, same connection) and I can't seem to figure out what's causing this.

Is anyone actively maintaining this repo and using it to export historical datasets? Getting the data from just the previous day seems to work fine.

### What I Did

- Tried various date ranges and formats
- Printed intermediate steps and results
- Different Python versions
- Tried small date ranges in the past and present

**Comment by veenstrajelmer** [comment]
@daveebbelaar could you please include a minimal working example in your issue?

**Comment by veenstrajelmer** [comment]
This seems to be a similar issue as decribed in https://github.com/openearth/ddlpy/issues/14#issuecomment-1028711332. There are two OLST stations containing grootheid Q. One contains a historic timeseries and one contains a realtime timeseries. I created this code to show the distinction:

```python
import ddlpy

locations = ddlpy.locations()
bool_stations = locations.index.isin(['OLST'])
bool_grootheid = locations['Grootheid.Code'].isin(['Q'])
selected = locations.loc[bool_stations & bool_grootheid]

# multiple parameters avaialble for this location, this is historic and realtime.
print(selected)

time_start = "2024-01-01"
time_end = "2024-04-01"

row0 = selected.iloc[0]
measurements0 = ddlpy.measurements(row0, time_start, time_end)
measurements0.plot(y='Meetwaarde.Waarde_Numeriek', linewidth=0.5, figsize=(13, 8))

row1 = selected.iloc[1]
measurements1 = ddlpy.measurements(row1, time_start, time_end)
measurements1.plot(y='Meetwaarde.Waarde_Numeriek', linewidth=0.5, figsize=(13, 8))
```

Creating this figure for the first station (historic):
![image](https://github.com/openearth/ddlpy/assets/60435591/b5d04b2e-e4ca-4df5-a199-cc8e51d1a8cc)

And this for the second (realtime)
![image](https://github.com/openearth/ddlpy/assets/60435591/b7d545a0-279f-451b-9f64-4c534e059b33)

I expect that you only checked the first station, which might on some platforms/environment be the second station since I am not sure what the ordering decides. I believe there is currently no generic way to distinguish between realtime and historic station.

Additional remark: it might happen that if you run this code in a month or so, the realtime query returns None. In that case just alter the time_end a bit.

With this I think this issue can be closed. If you disagree with this, please add an additional comment and/or re-open this issue.

**Comment by veenstrajelmer** [comment]
Another release of ddlpy was created today and all docs and examples were updated. Please open a new issue if you encounter any bugs.

**Comment by daveebbelaar** [comment]
Thanks @veenstrajelmer, I will look into this!
